### ISSUE TITLE
Reflex.Time.delay does not retain ordering

### ISSUE THREAD

**Issue by lspitzner** [reflex-frp/reflex#185] opened 2018-04-07 14:37 UTC
The current implementation of `delay` does not ensure that order of events is preserved through `delay`, due to race-condition when the delayed events fire (which thread gets the lock first).

I don't think this necessarily needs to be fixed, as fixing it seems to make the implementation much more complex. But it should at least be pointed out in the haddocks and the quickref.

**Comment by lspitzner** [comment] 2018-04-07 14:39
Combining `gateThrottle` from #184 and the current `delay` gives you a fixed `delay`, I think.

**Comment by dfordivam** [comment] 2019-01-25 07:31
I think there is no action item here, as the behavior is not a bug. So closing the issue.

**Closed by dfordivam** 2019-01-25 07:31 UTC
Labels: uncategorized
